version: '3.8'

services:
  draw-backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: xlike0616/draw-backend:latest
    ports:
      - "8000:8000"
    environment:
      - PYTHONPATH=/app
      - PYTHONUNBUFFERED=1
    restart: unless-stopped

  draw-frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
#        VITE_BACKEND_URL: http://localhost:8000
        VITE_BACKEND_URL: http://74.48.52.139:8000
    image: xlike0616/draw-frontend:latest
    ports:
      - "3000:80"
    depends_on:
      - draw-backend
    restart: unless-stopped
